[package]
authors = ['CypherHippie']
description = 'Certus-RPC'
edition = '2024'
name = 'certus-rpc'
homepage = "https://github.com/CerTusHack"
repository = "https://github.com/CerTusHack/Certus-Protocol-Node"
version = '1.0.0'

[package.metadata.docs.rs]
targets = ['x86_64-unknown-linux-gnu']

[dependencies]
certus-oracle-provider-support = { path = "../../pallets/certus-oracle-provider-support" }
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive", "max-encoded-len", ] }
chrono = "0.4"
serde = { version = "1.0.143", features = ["derive"] }
jsonrpc-core = "18.0.0"
jsonrpc-core-client = "18.0.0"
jsonrpc-pubsub = "18.0.0"
jsonrpc-derive = "18.0.0"
parking_lot = "0.11.2"
reqwest = { version = "0.11", features = ["blocking"] }
frame-support = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.6.0" }
sc-keystore = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.6.0" }
sc-service = { git = "https://github.com/paritytech/substrate", features = ['wasmtime'], branch = "polkadot-v1.6.0" }
sc-rpc = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.6.0" }
sc-rpc-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.6.0" }
sc-transaction-pool = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.6.0" }
sc-transaction-pool-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.6.0" }
serde_json = "1.0.74"
sp-api = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.6.0" }
sp-core = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.6.0" }
sp-blockchain = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.6.0" }
sp-session = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.6.0" }
sp-runtime = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.6.0" }
sp-io = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.6.0" }
sp-offchain = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.6.0" }
sp-keystore = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.6.0" }
thiserror = "1.0"
tokio = { version = "0.2", features = ["full"] }

[dev-dependencies]
substrate-test-runtime-client = { git = "https://github.com/paritytech/substrate", default-features = false, branch = "polkadot-v1.6.0" }
assert_matches = "1.3.0"